name: Scala CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up NPM 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Install npm deps
        run: cd frontend && npm install && cd ..
      - name: Compile
        run: sbt compile
      - name: Run tests
        run: sbt test
      - name: Build application
        run: sbt buildApplication
